import React, { FC } from "react";

import Head from "next/head";

const HeadView: FC = () => {
  return (
    <Head>
      <title>Take Home Test</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export { HeadView as Head };
