import React, { FC } from "react";
import Head from "next/head";
import { HeadModelProps } from "./types";

const HeadModel: FC<HeadModelProps> = ({
  title = "Test",
  content = "Generated by create next app",
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export { HeadModel as Head };
